#!/bin/bash
cd keyboard_heroes
git pull origin master
mix deps.get
export WORKSPACE=/home/brandon/
export APP=keyboard_heroes
mix edeliver build release
mix edeliver stop production
mix edeliver deploy release to production
mix edeliver migrate production
mix edeliver start production
